In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')
display(df.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [19]:
#data understanding
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [20]:

df.shape

(9994, 21)

In [22]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.shape

(9994, 21)

In [1]:
df.head(10)

NameError: name 'df' is not defined

In [8]:
df[['Sales','Profit','Quantity','Discount']].describe()

              Sales        Profit      Quantity      Discount
count  15410.000000  15410.000000  15410.000000  15410.000000
mean     229.095112     29.383084      3.785788      0.156059
std      615.032454    240.727256      2.218979      0.206517
min        0.444000  -6599.978000      1.000000      0.000000
25%       17.442500      1.724800      2.000000      0.000000
50%       54.920000      8.635200      3.000000      0.200000
75%      209.600000     29.495000      5.000000      0.200000
max    22638.480000   8399.976000     14.000000      0.800000

In [10]:
df.isnull().sum()

Row ID           0
Order ID         1
Order Date       1
Ship Date        1
Ship Mode        1
Customer ID      1
Customer Name    1
Segment          1
Country          1
City             1
State            1
Postal Code      1
Region           1
Product ID       1
Category         1
Sub-Category     1
Product Name     1
Sales            1
Quantity         1
Discount         1
Profit           1
dtype: int64

In [11]:

df.duplicated().sum()

np.int64(5416)

In [13]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [15]:
df['Order ID'].nunique()

5009

In [17]:
df['Customer ID'].nunique()

793

In [20]:
df['Country'].nunique()

1

In [23]:
df['City'].nunique()

531

In [25]:
df['Region'].nunique()

4

In [27]:
df['Category'].nunique()

3

In [29]:
df['Sub-Category'].nunique()

17

In [32]:
df['Category'].unique()

array(['Furniture', 'Office Supplies', 'Technology', nan], dtype=object)

In [33]:
# data quality assment

In [35]:
df.isnull().sum()

Row ID           0
Order ID         1
Order Date       1
Ship Date        1
Ship Mode        1
Customer ID      1
Customer Name    1
Segment          1
Country          1
City             1
State            1
Postal Code      1
Region           1
Product ID       1
Category         1
Sub-Category     1
Product Name     1
Sales            1
Quantity         1
Discount         1
Profit           1
dtype: int64

In [37]:
df['Order ID'].nunique()

5009

In [39]:
df['Customer ID'].nunique()

793

In [41]:
df['Product ID'].nunique()

1862

In [43]:
df['Category'].nunique()

3

In [45]:
df['Sub-Category'].nunique()

17

In [47]:
(df['Profit'] < 0).sum()

np.int64(2908)

In [49]:
(df['Quantity'] < 0).sum()

np.int64(0)

In [50]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         15411 non-null  int64
 1   Order ID       15410 non-null  object
 2   Order Date     15410 non-null  datetime64[ns]
 3   Ship Date      15410 non-null  datetime64[ns]
 4   Ship Mode      15410 non-null  object
 5   Customer ID    15410 non-null  object
 6   Customer Name  15410 non-null  object
 7   Segment        15410 non-null  object
 8   Country        15410 non-null  object
 9   City           15410 non-null  object
 10  State          15410 non-null  object
 11  Postal Code    15410 non-null  float64
 12  Region         15410 non-null  object
 13  Product ID     15410 non-null  object
 14  Category       15410 non-null  object
 15  Sub-Category   15410 non-null  object
 16  Product Name   15410 non-null  object
 17  Sales          15410 non-null  float64
 18  Quantity       15410 non-null  float64
 19  Discount       15410 non-null  float64
 20  Profit         15410 non-null  float64
dtypes: datetime64[ns](2), float64(5), int64(1), object(13)
memory usage: 2.5+ MB

In [54]:
(df['Profit'] < 0).sum()

np.int64(2908)

In [57]:
(df['Quantity'] < 0).sum()

np.int64(0)

In [59]:
(df['Ship Date'] < df['Order Date']).sum()

np.int64(0)

In [61]:
# Data Quality Assessment

## Data Completeness

The dataset contains no missing values across all 21 columns, indicating complete transactional records.

## Entity Overview

- 5009 unique orders
- 793 unique customers
- 1862 unique products
- 3 categories
- 17 sub-categories

## Data Consistency

- No invalid shipping dates detected.
- No negative quantities detected.
- Order and shipping records are logically consistent.

## Business Validation

2098 transactions generated negative profit, representing approximately 21% of all transactions.

This suggests that discounting, pricing strategy, or product costs may be impacting profitability and requires further investigation.

## Conclusion

The dataset is clean, consistent, and suitable for advanced business analytics and database modeling.

SyntaxError: invalid syntax (4116781545.py, line 5)

In [62]:
# data profiling

In [63]:
df['Sales'].sum()

np.float64(3530355.6787)

In [67]:
df['Sales'].mean()

np.float64(229.09511218040234)

In [70]:
df.nlargest( 1 , 'Sales')[['Order ID',
    'Customer Name',
    'Product Name',
    'Sales'
]]

,Order ID,Customer Name,Product Name,Sales
2697,CA-2014-145317,Sean Miller,Cisco TelePresence System EX90 Videoconferenci...,22638.48

In [71]:
df.nlargest( 10 , 'Sales')[['Order ID',
    'Customer Name',
    'Product Name',
    'Sales'
]]

,Order ID,Customer Name,Product Name,Sales
2697,CA-2014-145317,Sean Miller,Cisco TelePresence System EX90 Videoconferenci...,22638.480
6826,CA-2016-118689,Tamara Chand,Canon imageCLASS 2200 Advanced Copier,17499.950
12243,CA-2016-118689,Tamara Chand,Canon imageCLASS 2200 Advanced Copier,17499.950
8153,CA-2017-140151,Raymond Buch,Canon imageCLASS 2200 Advanced Copier,13999.960
13570,CA-2017-140151,Raymond Buch,Canon imageCLASS 2200 Advanced Copier,13999.960
2623,CA-2017-127180,Tom Ashbrook,Canon imageCLASS 2200 Advanced Copier,11199.968
4190,CA-2017-166709,Hunter Lopez,Canon imageCLASS 2200 Advanced Copier,10499.970
9039,CA-2016-117121,Adrian Barton,GBC Ibimaster 500 Manual ProClick Binding System,9892.740
14456,CA-2016-117121,Adrian Barton,GBC Ibimaster 500 Manual ProClick Binding System,9892.740
4098,CA-2014-116904,Sanjit Chand,Ibico EPK-21 Electric Binding System,9449.950

In [73]:
import plotly.express as px

fig = px.histogram(
    df,
    x='Sales',
    nbins=50,
    title='Sales Distribution'
)

fig.show()

In [75]:
df['Profit'].sum()

np.float64(452793.32519999996)

In [77]:
df['Profit'].mean()

np.float64(29.383084049318622)

In [78]:
df.nlargest(
    1,
    'Profit'
)[[
    'Product Name',
    'Profit'
]]

                               Product Name    Profit
6826  Canon imageCLASS 2200 Advanced Copier  8399.976

In [79]:
df.nsmallest(
    1,
    'Profit'
)[[
    'Product Name',
    'Profit'
]]

                                   Product Name    Profit
7772  Cubify CubeX 3D Printer Double Head Print -6599.978

In [81]:
fig = px.histogram(
    df,
    x='Profit',
    nbins=50,
    title='Profit Distribution'
)

fig.show()

In [82]:
df['Discount'].mean()

np.float64(0.1560590525632706)

In [83]:
df['Discount'].max()

0.8

In [84]:
df.nlargest(
    10,
    'Discount'
)[[
    'Product Name',
    'Discount'
]]

                                          Product Name  Discount
14   Holmes Replacement Filter for HEPA Air Cleaner...       0.8
15    Storex DuraTech Recycled Plastic Frosted Binders       0.8
75                                     Economy Binders       0.8
101      Avery Hidden Tab Dividers for Binding Systems       0.8
169       Kensington 7 Outlet MasterPiece Power Center       0.8
174  Kensington 7 Outlet MasterPiece HOMEOFFICE Pow...       0.8
176  Acco 7-Outlet Masterpiece Power Center, Wihtou...       0.8
203               Eureka Sanitaire  Commercial Upright       0.8
261  Eureka Disposable Bags for Sanitaire Vibra Gro...       0.8
280                                 Round Ring Binders       0.8

In [86]:
fig = px.histogram(
    df,
    x='Discount',
    title='Discount Distribution'
)

fig.show()

In [89]:
top_customers = (
    df.groupby(
        'Customer Name'
    )['Sales']
    .sum()
    .sort_values(
        ascending=False
    )
    .head(10)
)

top_customers

Customer Name
Tamara Chand          37996.726
Raymond Buch          29462.615
Adrian Barton         26132.101
Sean Miller           25890.454
Seth Vernon           21894.092
Sanjit Engle          21817.148
Christopher Conant    20895.980
Greg Tran             19414.852
Maria Etezadi         18874.072
Todd Sumrall          18747.768
Name: Sales, dtype: float64

In [91]:
fig = px.bar(
    top_customers,
    title='Top Customers by Sales'
)

fig.show()

In [95]:
df.groupby(
    'Customer Name'
)['Profit'].sum().sort_values(
    ascending=False
).head(10)

Customer Name
Tamara Chand        17977.4142
Raymond Buch        13783.1838
Adrian Barton       10318.1695
Sanjit Chand         6633.6869
Keith Dawkins        5767.6104
Hunter Lopez         5745.8840
Andy Reiter          5736.5075
Sanjit Engle         5713.0610
Daniel Raglin        5331.4654
Tom Boeckenhauer     5063.0652
Name: Profit, dtype: float64

In [98]:
df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          101499.7100
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     46772.4320
HON 5400 Series Task Chairs for Big and Tall                                    39184.7820
Hewlett Packard LaserJet 3310 Copier                                            35279.4120
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       34124.8050
GBC Ibimaster 500 Manual ProClick Binding System                                34091.9040
GBC DocuBind TL300 Electric Binding System                                      33726.8240
GBC DocuBind P400 Electric Binding System                                       28852.9880
High Speed Automatic Electric Letter Opener                                     25872.9740
Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish                   25742.2356
Name: Sales, dtype: float64

In [100]:
df.groupby(
    'Customer Name'
)['Profit'].sum().sort_values(
    ascending=False
).head(10)

Customer Name
Tamara Chand        17977.4142
Raymond Buch        13783.1838
Adrian Barton       10318.1695
Sanjit Chand         6633.6869
Keith Dawkins        5767.6104
Hunter Lopez         5745.8840
Andy Reiter          5736.5075
Sanjit Engle         5713.0610
Daniel Raglin        5331.4654
Tom Boeckenhauer     5063.0652
Name: Profit, dtype: float64

In [101]:
df.groupby(
    'Product Name'
)['Profit'].sum().sort_values(
    ascending=True
).head(10)

Product Name
Cubify CubeX 3D Printer Double Head Print                  -15479.9484
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases    -5884.4664
Lexmark MX611dhe Monochrome Laser Printer                   -4589.9730
Cubify CubeX 3D Printer Triple Head Print                   -3839.9904
Bush Advantage Collection Racetrack Conference Table        -2587.6810
O'Sullivan 4-Shelf Bookcase in Odessa Pine                  -2022.7856
GBC DocuBind P400 Electric Binding System                   -2014.2652
Balt Solid Wood Round Tables                                -1928.8368
Zebra GK420t Direct Thermal/Thermal Transfer Printer        -1876.5600
Cisco TelePresence System EX90 Videoconferencing Unit       -1811.0784
Name: Profit, dtype: float64

In [104]:
region_sales = (
    df.groupby(
        'Region'
    )['Sales']
    .sum()
    .sort_values(
        ascending=False
    )
)

region_sales

Region
West       1.121231e+06
East       1.050729e+06
Central    7.714922e+05
South      5.869034e+05
Name: Sales, dtype: float64

In [106]:
fig   = px.bar(
    region_sales,
    title='Sales by Region'
)

fig.show()

In [107]:
region_profit = (
    df.groupby(
        'Region'
    )['Profit']
    .sum()
    .sort_values(
        ascending=False
    )
)

region_profit

Region
West       173701.7911
East       142574.1581
South       72121.5102
Central     64395.8658
Name: Profit, dtype: float64

In [108]:
df.groupby(
    'State'
)['Sales'].sum().sort_values(
    ascending=False
).head(10)

State
California      711314.9965
New York        481859.0160
Texas           259082.0232
Washington      223757.3160
Pennsylvania    181922.3160
Florida         122345.8250
Illinois        121534.9220
Michigan        121133.6420
Ohio            120595.8340
Virginia        116096.5100
Name: Sales, dtype: float64

In [109]:
df.groupby(
    'State'
)['Profit'].sum().sort_values(
    ascending=False
).head(10)

State
California    120633.4863
New York      115960.5745
Washington     54737.7235
Michigan       40636.6891
Indiana        32149.8436
Virginia       31010.2716
Georgia        22395.1612
Kentucky       17656.1854
New Jersey     14026.8076
Minnesota      13502.0079
Name: Profit, dtype: float64

In [110]:
kpis = pd.DataFrame({

'Metric':[
'Total Sales',
'Total Profit',
'Total Orders',
'Total Customers',
'Total Products'
],

'Value':[

df['Sales'].sum(),

df['Profit'].sum(),

df['Order ID'].nunique(),

df['Customer ID'].nunique(),

df['Product ID'].nunique()

]

})

kpis

            Metric         Value
0      Total Sales  3.530356e+06
1     Total Profit  4.527933e+05
2     Total Orders  5.009000e+03
3  Total Customers  7.930000e+02
4   Total Products  1.862000e+03

In [111]:
df['Profit_Margin'] = (
    df['Profit']
    /
    df['Sales']
) * 100

In [113]:
df['Profit_Margin'].describe()

count    15410.000000
mean        11.893967
std         46.953022
min       -275.000000
25%          7.500000
50%         27.000000
75%         36.250000
max         50.000000
Name: Profit_Margin, dtype: float64

In [115]:
df.groupby(
    'Product Name'
)['Profit_Margin'].mean().sort_values(
    ascending=False
).head(10)

Product Name
Tops Green Bar Computer Printout Paper                                                   50.0
Canon imageCLASS MF7460 Monochrome Digital Laser Multifunction Copier                    50.0
Southworth Structures Collection                                                         50.0
Avery 475                                                                                50.0
Xerox 1890                                                                               50.0
Adams Telephone Message Book w/Frequently-Called Numbers Space, 400 Messages per Book    50.0
Avery 5                                                                                  49.0
Xerox 1918                                                                               49.0
Xerox 1983                                                                               49.0
Color-Coded Legal Exhibit Labels                                                         49.0
Name: Profit_Margin, dtype: float64

In [116]:
df.groupby(
    'Product Name'
)['Profit_Margin'].mean().sort_values(
    ascending=True
).head(10)

Product Name
Eureka Disposable Bags for Sanitaire Vibra Groomer I Upright Vac           -275.000000
Bush Westfield Collection Bookcases, Dark Cherry Finish, Fully Assembled   -210.000000
Euro Pro Shark Stick Mini Vacuum                                           -177.500000
Acco 6 Outlet Guardian Basic Surge Suppressor                              -164.000000
Okidata B401 Printer                                                       -140.000000
3.6 Cubic Foot Counter Height Office Refrigerator                          -136.000000
Zebra GK420t Direct Thermal/Thermal Transfer Printer                       -133.333333
Hoover Commercial Lightweight Upright Vacuum                               -131.250000
Tripp Lite Isotel 8 Ultra 8 Outlet Metal Surge                             -126.625000
Kensington 6 Outlet SmartSocket Surge Protector                            -125.000000
Name: Profit_Margin, dtype: float64

In [118]:


fig = px.histogram(
    df,
    x='Profit_Margin',
    nbins=50,
    title='Profit Margin Distribution'
)

fig.show()

In [122]:
df['Profit_Margin'] = (
    df['Profit']
    /
    df['Sales']
) * 100
df['Profit_Margin']

0        16.00
1        30.00
2        47.00
3       -40.00
4        11.25
         ...
15406    16.25
15407    17.00
15408     7.50
15409    45.00
15410    30.00
Name: Profit_Margin, Length: 15411, dtype: float64

In [123]:
fig = px.histogram(
    df,
    x='Profit_Margin',
    nbins=50,
    title='Profit Margin Distribution'
)

fig.show()

In [126]:
pareto_df = (
    df.groupby(
        'Customer Name'
    )['Sales']
    .sum()
    .sort_values(
        ascending=False
    )
    .reset_index()
)

pareto_df.head()

   Customer Name      Sales
0   Tamara Chand  37996.726
1   Raymond Buch  29462.615
2  Adrian Barton  26132.101
3    Sean Miller  25890.454
4    Seth Vernon  21894.092

In [127]:
pareto_df['Cumulative_Sales'] = (
    pareto_df['Sales']
    .cumsum()
)

pareto_df['Cumulative_Percentage'] = (
    pareto_df['Cumulative_Sales']
    /
    pareto_df['Sales'].sum()
) * 100

In [128]:
fig = px.line(
    pareto_df,
    x=pareto_df.index,
    y='Cumulative_Percentage',
    title='Customer Revenue Pareto Analysis'
)

fig.show()

In [129]:
df[['Discount','Profit']].corr()

          Discount    Profit
Discount  1.000000 -0.214189
Profit   -0.214189  1.000000

In [130]:
fig = px.scatter(
    df,
    x='Discount',
    y='Profit',
    title='Discount vs Profit'
)

fig.show()

In [131]:
df['Shipping_Days'] = (
    df['Ship Date']
    -
    df['Order Date']
).dt.days

In [132]:
df['Shipping_Days'].mean()

np.float64(3.9600259571706684)

In [133]:
df.groupby(
    'Ship Mode'
)['Shipping_Days'].mean().sort_values()

Ship Mode
Same Day          0.041568
First Class       2.188060
Second Class      3.226023
Standard Class    5.003571
Name: Shipping_Days, dtype: float64

In [134]:
fig = px.box(
    df,
    x='Ship Mode',
    y='Shipping_Days',
    title='Shipping Days by Ship Mode'
)

fig.show()

In [136]:
# DATABASE DESIGN
import pandas as pd

try:
    df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')
    print("Data loaded successfully.")
    display(df.head())
except Exception as e:
    print(f"Error loading data: {e}")

In [139]:
#customer
customers = (
    df[
        [
            'Customer ID',
            'Customer Name',
            'Segment'
        ]
    ]
    .drop_duplicates()
)

customers.head()

   Customer ID    Customer Name    Segment
0     CG-12520      Claire Gute   Consumer
2     DV-13045  Darrin Van Huff  Corporate
3     SO-20335   Sean O'Donnell   Consumer
5     BH-11710  Brosina Hoffman   Consumer
12    AA-10480     Andrew Allen   Consumer

In [143]:
customers.shape

(794, 3)

In [145]:
products = (
    df[
        [
            'Product ID',
            'Category',
            'Sub-Category',
            'Product Name'
        ]
    ]
    .drop_duplicates()
)

In [146]:
products.shape

(1895, 4)

In [147]:
orders = (
    df[
        [
            'Order ID',
            'Order Date',
            'Ship Date',
            'Ship Mode',
            'Customer ID',
            'Product ID',
            'Country',
            'City',
            'State',
            'Region',
            'Sales',
            'Quantity',
            'Discount',
            'Profit'
        ]
    ]
)

orders.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Product ID,Country,City,State,Region,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-BO-10001798,United States,Henderson,Kentucky,South,261.9600,2.0,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-CH-10000454,United States,Henderson,Kentucky,South,731.9400,3.0,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,OFF-LA-10000240,United States,Los Angeles,California,West,14.6200,2.0,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,FUR-TA-10000577,United States,Fort Lauderdale,Florida,South,957.5775,5.0,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,OFF-ST-10000760,United States,Fort Lauderdale,Florida,South,22.3680,2.0,0.20,2.5164

In [149]:
orders.shape

(15411, 14)

In [150]:
#ER diagarm
CUSTOMERS
-----------
Customer_ID (PK)
Customer_Name
Segment


PRODUCTS
-----------
Product_ID (PK)
Product_Name
Category
Sub_Category


ORDERS
-----------
Order_ID
Order_Date
Ship_Date
Ship_Mode

Customer_ID (FK)
Product_ID (FK)

Country
City
State
Region

Sales
Quantity
Discount
Profit

SyntaxError: invalid syntax (1375906248.py, line 3)

In [185]:
customers.to_csv(
    'customers.csv',
    index=False
)

products.to_csv(
    'products.csv',
    index=False
)

orders.to_csv(
    'orders.csv',
    index=False
)

In [187]:
customers.to_csv(
    'customers.csv',
    index=False
)

products.to_csv(
    'products.csv',
    index=False
)

orders.to_csv(
    'orders.csv',
    index=False
)

In [160]:
len(customers)

794

In [162]:
customers['Customer ID'].duplicated().sum()

np.int64(0)

In [164]:
customers['Customer ID'].isna().sum()

np.int64(1)

In [166]:
customers['Customer ID'].nunique(dropna=False)

794

In [168]:
customers['Customer ID'].nunique(dropna=True)

793

In [170]:
products['Product ID'].nunique()

1862

In [172]:
len(products)

1895

In [174]:
products['Product ID'].duplicated().sum()

np.int64(32)

In [178]:
products['Product ID'].duplicated().drop_duplicates().sum()

np.int64(1)

In [181]:
products['Product ID'].nunique(dropna=True)

1862

In [189]:
customers = customers.dropna(how='all')

customers.to_csv(
    'customers.csv',
    index=False
)

In [191]:
with open('customers.csv', 'r', encoding='utf-8') as f:
    lines = f.readlines()

print("Total lines:", len(lines))
print("Last 5 lines:")
for line in lines[-5:]:
    print(repr(line))

Total lines: 794
Last 5 lines:
'CJ-11875,Carl Jackson,Corporate\n'
'RS-19870,Roy Skaria,Home Office\n'
'SC-20845,Sung Chung,Consumer\n'
'RE-19405,Ricardo Emerson,Consumer\n'
'SM-20905,Susan MacKendrick,Consumer\n'

In [194]:
customers = customers.dropna(how='all')
products = products.dropna(how='all')
orders = orders.dropna(how='all')

customers.to_csv(
    'customers.csv',
    index=False,
    encoding='utf-8'
)

products.to_csv(
    'products.csv',
    index=False,
    encoding='utf-8'
)

orders.to_csv(
    'orders.csv',
    index=False,
    encoding='utf-8'
)

In [196]:
print(customers.shape)
print(products.shape)
print(orders.shape)

(793, 3)
(1894, 4)
(15410, 14)

In [198]:
customers.isna().sum()

Customer ID      0
Customer Name    0
Segment          0
dtype: int64

In [200]:
products.isna().sum()

Product ID      0
Category        0
Sub-Category    0
Product Name    0
dtype: int64

In [202]:
customers[customers.isna().any(axis=1)]

Empty DataFrame
Columns: [Customer ID, Customer Name, Segment]
Index: []

In [204]:
products[products.isna().any(axis=1)]

Empty DataFrame
Columns: [Product ID, Category, Sub-Category, Product Name]
Index: []

In [209]:
orders['Quantity'] = (
    orders['Quantity']
    .astype(int)
)


orders.to_csv(
    'orders.csv',
    index=False
)

In [212]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 793 entries, 0 to 9558
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    793 non-null    object
 1   Customer Name  793 non-null    object
 2   Segment        793 non-null    object
dtypes: object(3)
memory usage: 24.8+ KB

In [214]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 793 entries, 0 to 9558
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    793 non-null    object
 1   Customer Name  793 non-null    object
 2   Segment        793 non-null    object
dtypes: object(3)
memory usage: 24.8+ KB

In [216]:
products = products.astype(str)

products.to_csv(
    'products_final.csv',
    index=False
)

In [218]:
customers = customers.astype(str)

customers.to_csv(
    'customers_final.csv',
    index=False
)

In [222]:


orders.to_csv('orders.csv', index=False)

In [224]:
orders.shape

(15410, 14)

In [227]:
customers.shape

(793, 3)

In [229]:
products.shape

(1894, 4)

In [231]:
customers = (
    df[
        [
            'Customer ID',
            'Customer Name',
            'Segment'
        ]
    ]
    .drop_duplicates()
)

customers.shape

(794, 3)

In [232]:
products = (
    df[
        [
            'Product ID',
            'Product Name',
            'Category',
            'Sub-Category'
        ]
    ]
    .drop_duplicates()
)

products.shape

(1895, 4)

In [234]:
orders = (
    df[
        [
            'Order ID',
            'Order Date',
            'Ship Date',
            'Ship Mode',
            'Customer ID',
            'Product ID',
            'Country',
            'City',
            'State',
            'Region',
            'Sales',
            'Quantity',
            'Discount',
            'Profit'
        ]
    ]
)

In [236]:
orders.shape

(15411, 14)

In [241]:
import pandas as pd

# Load the dataset with correct encoding
df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')

# Define Customers table
customers = df[['Customer ID', 'Customer Name', 'Segment']].drop_duplicates()

# Define Products table
products = df[['Product ID', 'Product Name', 'Category', 'Sub-Category']].drop_duplicates()

# Define Orders table
orders = df[[
    'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
    'Customer ID', 'Product ID', 'Country', 'City',
    'State', 'Region', 'Sales', 'Quantity', 'Discount', 'Profit'
]]

print(f"Data loaded. Customers: {customers.shape}, Products: {products.shape}, Orders: {orders.shape}")
display(customers.head())

Data loaded. Customers: (794, 3), Products: (1895, 4), Orders: (15411, 14)

   Customer ID    Customer Name    Segment
0     CG-12520      Claire Gute   Consumer
2     DV-13045  Darrin Van Huff  Corporate
3     SO-20335   Sean O'Donnell   Consumer
5     BH-11710  Brosina Hoffman   Consumer
12    AA-10480     Andrew Allen   Consumer

In [243]:
products.shape

(1895, 4)

In [245]:
orders.shape

(15411, 14)

In [247]:
customers.shape

(794, 3)

In [249]:
df.shape

(15411, 21)

In [251]:
df.duplicated().sum()

np.int64(5416)

In [253]:
df.shape

(15411, 21)

In [255]:
df = df.drop_duplicates()

In [257]:
df.shape

(9995, 21)

In [259]:
df.dropna(inplace=True)

In [260]:
df.shape

(9994, 21)

In [13]:
customers = (
    df[
        [
            'Customer ID',
            'Customer Name',
            'Segment'
        ]
    ]
    .drop_duplicates()
)

customers.shape

(794, 3)

In [12]:
products = (
    df[
        [
            'Product ID',
            'Product Name',
            'Category',
            'Sub-Category'
        ]
    ]
    .drop_duplicates()
)

products.shape

(1895, 4)

In [266]:
products.drop_duplicates(inplace=True)

In [268]:
products.shape

(1894, 4)

In [269]:
products.duplicated().sum()

np.int64(0)

In [273]:
products.dropna(inplace=True)

In [275]:
products.shape

(1894, 4)

In [15]:
orders = (
    df[
        [
            'Order ID',
            'Order Date',
            'Ship Date',
            'Ship Mode',
            'Customer ID',
            'Product ID',
            'Country',
            'City',
            'State',
            'Region',
            'Sales',
            'Quantity',
            'Discount',
            'Profit'
        ]
    ]
)

orders.shape

(15411, 14)

In [16]:
products.duplicated().sum() == 0

np.True_

In [17]:
products.duplicated().sum() == 0

np.True_

In [21]:
orders.drop_duplicates(inplace=True)

/tmp/ipykernel_3538/2944507438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders.drop_duplicates(inplace=True)

In [23]:
orders.duplicated().sum()

np.int64(0)

In [24]:
orders.shape

(9994, 14)

In [26]:
orders.shape

(9994, 14)

In [28]:
products.shape

(1895, 4)

In [30]:
customers.shape

(794, 3)

In [33]:
customers.to_csv(
    'customers_clean.csv',
    index=False
)

products.to_csv(
    'products_clean.csv',
    index=False
)

orders.to_csv(
    'orders_clean.csv',
    index=False
)

In [36]:
orders['Order Date'] = pd.to_datetime(
    orders['Order Date']
)

orders['Ship Date'] = pd.to_datetime(
    orders['Ship Date']
)

/tmp/ipykernel_3538/1288836518.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['Order Date'] = pd.to_datetime(
/tmp/ipykernel_3538/1288836518.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['Ship Date'] = pd.to_datetime(

In [41]:
orders['Order Date'] = (
    orders['Order Date']
    .dt.strftime('%Y-%m-%d')
)

orders['Ship Date'] = (
    orders['Ship Date']
    .dt.strftime('%Y-%m-%d')
)

AttributeError: Can only use .dt accessor with datetimelike values

In [42]:
orders.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Product ID,Country,City,State,Region,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-BO-10001798,United States,Henderson,Kentucky,South,261.9600,2.0,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-CH-10000454,United States,Henderson,Kentucky,South,731.9400,3.0,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,OFF-LA-10000240,United States,Los Angeles,California,West,14.6200,2.0,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,FUR-TA-10000577,United States,Fort Lauderdale,Florida,South,957.5775,5.0,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,OFF-ST-10000760,United States,Fort Lauderdale,Florida,South,22.3680,2.0,0.20,2.5164

In [45]:
orders.to_csv(
    'orders_final.csv',
    index=False
)